CREATE TYPE difficulty_level AS ENUM ('BEGINNER', 'MEDIUM', 'HARD');
CREATE TYPE story_status AS ENUM ('PENDING_REVIEW', 'PUBLISHED', 'DRAFT');
CREATE TYPE author_type AS ENUM ('AI_GENERATED', 'ADMIN');
CREATE TYPE goal_category AS ENUM (
    'EMERGENCY', 'EDUCATION', 'TRAVEL', 'ELECTRONICS',
    'HOME', 'TRANSPORTATION', 'HEALTH', 'ENTERTAINMENT',
    'INVESTMENT', 'OTHER'
);
CREATE TYPE story_category AS ENUM (
    'INVESTING', 'SAVING', 'RETIREMENT', 'DEBT', 'BUSINESS'
);
CREATE TYPE transaction_type AS ENUM ('BUY', 'SELL');